version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=ledgers
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db-data:/var/lib/postgresql
    ports:
      - 5433:5432

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6389:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./redis:/data      